name = "api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["1 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "waffle-db"
database_id = "73e484fc-2692-4cce-b9c7-ea0aa3579157"
