// Phrazle phrases database - extracted from solitaired.com
// Reference date: April 18, 2022 (the game's start date)
// Formula: gameNumber = 2 * days_since_ref + (hour < 12 ? 1 : 2)
// Phrase index = gameNumber % TOTAL_PHRASES

export const PHRASES: string[] = [
  "happy as a clam",
  "i smell a rat",
  "the butt of the joke",
  "deal with it",
  "monkey see monkey do",
  "baptism by fire",
  "hand in hand",
  "double down",
  "a catch twenty two",
  "a conniption fit",
  "take the bull by the horns",
  "following suit",
  "foregone conclusion",
  "the bees knees",
  "cut and dry",
  "down the rabbit hole",
  "dollars to donuts",
  "against the grain",
  "my birthday suit",
  "fool me once",
  "fortune favors the bold",
  "caught me red handed",
  "bag of tricks",
  "the dogs of war",
  "beware the ides of march",
  "drop in the bucket",
  "familiarity breeds contempt",
  "until the cows come home",
  "case in point",
  "tit for tat",
  "nuts and bolts",
  "cold hearted",
  "lost in translation",
  "off kilter",
  "if the shoe fits",
  "reap what you sow",
  "pie in the sky",
  "give it your best shot",
  "break a leg",
  "glass ceiling",
  "too good to pass up",
  "a bad egg",
  "food for thought",
  "maiden voyage",
  "rose colored glasses",
  "doing it by the book",
  "in fits and starts",
  "on point",
  "to know by heart",
  "hold your horses",
  "the lions share",
  "pick up the tab",
  "in for a penny in for a pound",
  "all over the board",
  "use your noodle",
  "rake me over the coals",
  "from rags to riches",
  "on the same page",
  "a poison pill",
  "fly by the seat of your pants",
  "let sleeping dogs lie",
  "heavens to betsy",
  "a penny for your thoughts",
  "soup to nuts",
  "once in a blue moon",
  "take five",
  "make a mountain of a molehill",
  "trial balloon",
  "dressed to kill",
  "know which way the wind blows",
  "rock the boat",
  "to a tee",
  "rest assured",
  "put yourself in my shoes",
  "in over my head",
  "bogged down",
  "my neck of the woods",
  "thumbs up",
  "three sheets to the wind",
  "out the door",
  "hand me down",
  "clam up",
  "bringing home the bacon",
  "better late than never",
  "all in a days work",
  "dropping like flies",
  "a head start",
  "going south",
  "in memory of",
  "a day late and a dollar short",
  "sticky wicket",
  "up the ante",
  "face the music",
  "extenuating circumstances",
  "as a rule of thumb",
  "with a fine toothed comb",
  "piqued my interest",
  "giddy up",
  "a pound of flesh",
  "faint of heart",
  "a stitch in time saves nine",
  "tie the knot",
  "a race against time",
  "in hot water",
  "the birds and the bees",
  "get out of dodge",
  "curry favor",
  "flat broke",
  "spill the beans",
  "i was robbed",
  "all your eggs in one basket",
  "rain on my parade",
  "take it with a grain of salt",
  "good grief",
  "spice things up",
  "sneak peek",
  "an old hand",
  "yes man",
  "round robin",
  "a gray area",
  "birds of a feather",
  "roll out the red carpet",
  "put your thinking cap on",
  "ace in the hole",
  "making ends meet",
  "cash strapped",
  "mind your ps and qs",
  "a green thumb",
  "in the dog house",
  "get out of jail free card",
  "going cold turkey",
  "rule of thumb",
  "mums the word",
  "pull up your socks",
  "across the board",
  "letting my hair down",
  "dumpster fire",
  "egging me on",
  "passing the buck",
  "put a sock in it",
  "off the cuff",
  "all things being equal",
  "out to lunch",
  "salt of the earth",
  "in a jam",
  "go to bat for",
  "a banner year",
  "out of the woods",
  "finger pointing",
  "be all and end all",
  "come out in the wash",
  "calling the shots",
  "think tank",
  "green with envy",
  "nest egg",
  "wearing my heart on my sleeve",
  "in a nutshell",
  "after the fact",
  "silence is golden",
  "hit the road",
  "hunker down",
  "a cup of joe",
  "all over the place",
  "live long and prosper",
  "first dibs",
  "hat trick",
  "learning the ropes",
  "get into the full swing",
  "horsing around",
  "great minds think alike",
  "kit and caboodle",
  "dead as a doornail",
  "all it is cracked up to be",
  "ahead of the game",
  "and bob is your uncle",
  "dressed to the nines",
  "ball and chain",
  "pinch pennies",
  "crunching the numbers",
  "fingers crossed",
  "practice makes perfect",
  "a card up my sleeve",
  "ahead of the curve",
  "survival of the fittest",
  "loose lips sink ships",
  "crocodile tears",
  "silver tongue",
  "last but not least",
  "priced out of the market",
  "hit below the belt",
  "on the bubble",
  "taking a flyer",
  "spur of the moment",
  "keeping your head above water",
  "ins and outs",
  "the powers that be",
  "hair of the dog",
  "roll up your sleeves",
  "woe is me",
  "lo and behold",
  "houston we have a problem",
  "my two cents",
  "my bread and butter",
  "a moot point",
  "head over heels",
  "i will be your huckleberry",
  "red in tooth and claw",
  "fair winds and following seas",
  "movers and shakers",
  "tried and true",
  "a sticking point",
  "the world is your oyster",
  "i am checked out",
  "cut me some slack",
  "stick your neck out",
  "all riled up",
  "keep it zipped",
  "telling white lies",
  "moving up in the world",
  "the gravy train",
  "barking up the wrong tree",
  "chop chop",
  "kill two birds with one stone",
  "fight fire with fire",
  "a bun in the oven",
  "head in the clouds",
  "fig leaf",
  "cut to the chase",
  "an uphill climb",
  "the calm before the storm",
  "taking a cat nap",
  "a fair weather friend",
  "nickel and dimed",
  "sleep tight",
  "right hand man",
  "jack of all trades",
  "short end of the stick",
  "black and blue",
  "a bee in my bonnet",
  "a change of heart",
  "paint the town red",
  "out of the blue",
  "getting sacked",
  "silver lining",
  "you hit the nail on the head",
  "black sheep",
  "thick as thieves",
  "the bearer of bad news",
  "deliver the goods",
  "off the beaten path",
  "hand over fist",
  "seeing red",
  "err on the side of caution",
  "pretty penny",
  "pay through the nose",
  "double dipping",
  "bury the hatchet",
  "to no avail",
  "the dynamic duo",
  "all told",
  "riding my coattails",
  "a clarion call",
  "over my dead body",
  "take it to the bank",
  "put me in my place",
  "show your true colors",
  "on the nose",
  "race against the clock",
  "all hands on deck",
  "hook line and sinker",
  "born with a silver spoon",
  "when it rains it pours",
  "white elephant",
  "a piece of cake",
  "have my cake and eat it too",
  "eat your heart out",
  "sold on something",
  "wax poetic",
  "back and forth",
  "tongue in cheek",
  "skinny dipping",
  "my flesh and blood",
  "a golden opportunity",
  "that is all folks",
  "rat race",
  "black and white",
  "no rest for the wicked",
  "for better or for worse",
  "play it by ear",
  "by hook or by crook",
  "make a beeline",
  "pulling my leg",
  "thank god it is friday",
  "drive a wedge between",
  "bet your bottom dollar",
  "handle with kid gloves",
  "i am all ears",
  "pipe dream",
  "my back is against the wall",
  "home is where the heart is",
  "slings and arrows",
  "tip my hat",
  "double edged sword",
  "at my beck and call",
  "rubber stamp",
  "lend me a hand",
  "get it off your chest",
  "the last straw",
  "light at the end of the tunnel",
  "raising red flags",
  "it was a dark and stormy night",
  "curiosity killed the cat",
  "cat got your tongue",
  "burning the midnight oil",
  "business as usual",
  "put me on the spot",
  "crying over spilled milk",
  "tilting at windmills",
  "copy cat",
  "read between the lines",
  "my lips are sealed",
  "knock on wood",
  "all that glitters is not gold",
  "taken aback",
  "stay tuned",
  "light a fire under him",
  "knight in shining armor",
  "measure up",
  "caught red handed",
  "give and take",
  "be there or be square",
  "getting the green light",
  "trials and tribulations",
  "close but no cigar",
  "halcyon days",
  "driving a hard bargain",
  "off the hook",
  "on the shoulders of giants",
  "misery loves company",
  "buckle down",
  "the whole nine yards",
  "all things considered",
  "at the drop of a hat",
  "grasping at straws",
  "over the hill",
  "hustle and bustle",
  "sticker shock",
  "the cream of the crop",
  "the elephant in the room",
  "two a penny",
  "tools of the trade",
  "passing with flying colors",
  "sweeten the deal",
  "a silver bullet",
  "a blank check",
  "on cloud nine",
  "deep pockets",
  "buy it for a song",
  "ants in your pants",
  "a line in the sand",
  "heads will roll",
  "a bad apple",
  "going downhill",
  "tooth and nail",
  "diamond in the rough",
  "cutting corners",
  "below the belt",
  "the whole shebang",
  "cost an arm and a leg",
  "i am tickled pink",
  "chicken out",
  "flying by the seat of my pants",
  "living the dream",
  "a sweet tooth",
  "in the works",
  "pomp and circumstance",
  "do as i say not as i do",
  "all is fair in love and war",
  "big deal",
  "think outside the box",
  "blow the competition away",
  "hanging on by a thread",
  "winner winner chicken dinner",
  "up the creek",
  "beet red",
  "one smart cookie",
  "up to par",
  "a chip on your shoulder",
  "let the cat out of the bag",
  "playing hot potato",
  "dig deep",
  "cat burglar",
  "get down to brass tacks",
  "ebb and flow",
  "crash and burn",
  "cry your heart out",
  "two peas in a pod",
  "skin in the game",
  "in the dark",
  "walk the plank",
  "rain check",
  "to each their own",
  "the apple of my eye",
  "out of work",
  "raining cats and dogs",
  "there is the rub",
  "hit the hay",
  "a second wind",
  "cut the gordian knot",
  "coming to terms with",
  "you are what you eat",
  "up in the air",
  "shot in the dark",
  "par for the course",
  "red tape",
  "money talks",
  "sea change",
  "my achilles heel",
  "seize the day",
  "cash and carry",
  "hang in there",
  "start with a clean slate",
  "beck and call",
  "open sesame",
  "selling like hot cakes",
  "ignorance is bliss",
  "the big cheese",
  "turning on a dime",
  "taking the red eye",
  "flotsam and jetsam",
  "pig out",
  "on a silver platter",
  "a chunk of change",
  "hasta la vista baby",
  "getting cold feet",
  "big picture",
  "take it or leave it",
  "for whom the bell tolls",
  "pound sand",
  "burn the candle at both ends",
  "stupid is as stupid does",
  "long in the tooth",
  "on a roll",
  "pencil me in",
  "an eager beaver",
  "keep an eye on it",
  "get to grips with",
  "a good bang for your buck",
  "stumbling block",
  "keep your chin up",
  "wrapped around your finger",
  "in the red",
  "fish or cut bait",
  "back to the drawing board",
  "my cup runneth over",
  "lickety split",
  "down to earth",
  "wreak havoc",
  "pink slip",
  "standing my ground",
  "dog days",
  "a dime a dozen",
  "bite the bullet",
  "cool as a cucumber",
  "shed some light",
  "in the fullness of time",
  "in the pipeline",
  "out of the loop",
  "no man is an island",
  "by the skin of my teeth",
  "with bated breath",
  "a pat on the back",
  "buttering me up",
  "not my cup of tea",
  "it makes my blood boil",
  "the benefit of the doubt",
  "the spur of the moment",
  "take a rain check",
  "death and taxes",
  "seeing eye to eye",
  "blood is thicker than water",
  "jump the shark",
  "youth is wasted on the young",
  "blind sided",
  "as quick as lightning",
  "writ large",
  "the bane of my existence",
  "on the lam",
  "a little bird told me",
  "get down to business",
  "chalk it up to",
  "double or nothing",
  "tee off",
  "earning brownie points",
  "a hard nut to crack",
  "reach for the stars",
  "taking the edge off",
  "bar none",
  "have the upper hand",
  "above water",
  "rank and file",
  "nip it in the bud",
  "first and foremost",
  "it smells fishy",
  "cheaper by the dozen",
  "back to the salt mines",
  "kick the can down the road",
  "second to none",
  "one fell swoop",
  "burning a hole in my pocket",
  "bursting at the seams",
  "sweet nothings",
  "back in the saddle",
  "fits like a glove",
  "a fair shake",
  "vice versa",
  "time flies",
  "preaching to the choir",
  "a kangaroo court",
  "back to square one",
  "all in all",
  "a stick in the mud",
  "down to the wire",
  "hit a snag",
  "win by a landslide",
  "take for granted",
  "a bridge too far",
  "beyond the pale",
  "bare necessities",
  "i have bigger fish to fry",
  "the buck stops here",
  "all over the map",
  "bats in the belfry",
  "holy cow",
  "the front runner",
  "keep on trucking",
  "elevator pitch",
  "crunch time",
  "toe the line",
  "you snooze you lose",
  "let there be light",
  "changing of the guard",
  "way to go",
  "lock stock and barrel",
  "by and large",
  "cross your ts and dot your is",
  "call it a day",
  "a run for my money",
  "the eleventh hour",
  "ahead of their time",
  "vim and vigor",
  "dirt cheap",
  "up for grabs",
  "under the weather",
  "go with the flow",
  "the tip of the iceberg",
  "penny pinching",
  "go off the rails",
  "to each his own",
  "all over but the shouting",
  "bet the farm",
  "acid test",
  "to iron out",
  "run into a buzz saw",
  "five finger discount",
  "all set",
  "snake oil salesman",
  "act your age",
  "get with the program",
  "move up in the world",
  "all fur coat and no knickers",
  "just for the record",
  "albatross around my neck",
  "speak of the devil",
  "low hanging fruit",
  "window dressing",
  "take a hike",
  "you know the drill",
  "blow the whistle",
  "one foot in the grave",
  "get my hands dirty",
  "burn the midnight oil",
  "the whole enchilada",
  "does that ring a bell",
  "on the mend",
  "birds of a feather",
  "chasing rainbows",
  "all roads lead to rome",
  "nothing to write home about",
  "a piece of cake",
  "a chip off the old block",
  "fishing for compliments",
  "freudian slip",
  "throw caution to the wind",
  "a match made in heaven",
  "the story has legs",
  "take the edge off",
  "go off the deep end",
  "dry run",
  "a sight for sore eyes",
  "dog days of the summer",
  "throw the fight",
  "heard it through the grapevine",
  "point the finger",
  "about time",
  "swing for the fences",
  "sleeping like a baby",
  "come hell or high water",
  "a sitting duck",
  "a million and one",
  "pull some strings",
  "blue blood",
  "back on my feet",
  "get the ball rolling",
  "sleep with the fishes",
  "a life of its own",
  "lipstick on a pig",
  "pay an arm and a leg",
  "all the same",
  "up in arms",
  "beat me to the punch",
  "let my hair down",
  "be a peach",
  "run the table",
  "stem the tide",
  "hang it up",
  "take a rain check",
  "under wraps",
  "get the picture",
  "in the cards",
  "pushing up daisies",
  "go down in flames",
  "six ways to sunday",
  "shape up or ship out",
  "take it with a grain of salt",
  "pass with flying colors",
  "give the green light",
  "bet my bottom dollar",
  "reinvent the wheel",
  "cool as a cucumber",
  "circle the wagons",
  "selling like hotcakes",
  "an ace up my sleeve",
  "king of the hill",
  "apples and oranges",
  "train wreck",
  "as american as apple pie",
  "big apple",
  "a hard nut to crack",
  "put out some feelers",
  "let bygones be bygones",
  "hive mind",
  "scorched earth policy",
  "get off scot free",
  "in a new york minute",
  "above board",
  "heart and soul",
  "happy go lucky",
  "butterflies in my stomach",
  "put your foot down",
  "bang for your buck",
  "mad as a hatter",
  "give it a whirl",
  "window shopping",
  "rear its ugly head ",
  "clip my wings",
  "nine times out of ten",
  "time is money",
  "push the envelope",
  "living on borrowed time",
  "pep talk",
  "give them the old heave ho",
  "keep your nose clean",
  "play your cards right",
  "take the gloves off",
  "neck and neck",
  "sacred cow",
  "dead as the dodo",
  "stand your ground",
  "turn turtle",
  "young at heart",
  "backseat driver",
  "through thick and thin",
  "show your cards",
  "a change of heart",
  "pot calling the kettle black",
  "sink or swim",
  "fly by the seat of my pants",
  "rob peter to pay paul",
  "run a tight ship",
  "when pigs fly",
  "throw in the towel",
  "steal my thunder",
  "ballpark figure",
  "the time of your life",
  "saving grace",
  "cool your jets",
  "cross to bear",
  "go bonkers",
  "twenty four seven",
  "a vicious circle",
  "follow in my footsteps",
  "tough cookie",
  "the only game in town",
  "throw me for a loop",
  "buy a pig in a poke",
  "fifteen minutes of fame",
  "pencil it in",
  "dyed in the wool",
  "a screw loose",
  "all in one piece",
  "blow my stack",
  "riding high",
  "larger than life",
  "cry over spilled milk",
  "playing cat and mouse",
  "take the shine off",
  "neck of the woods",
  "you can say that again",
  "use your head",
  "a rookie mistake",
  "the time is ripe",
  "a slam dunk",
  "foul play",
  "sword of damocles",
  "zero in on",
  "stiff upper lip",
  "a rare bird",
  "long shot",
  "tone deaf",
  "stick it to the man",
  "of two minds",
  "waiting in the wings",
  "the walls have ears",
  "sweep under the rug",
  "lose touch",
  "take the wind out of my sails",
  "right as rain",
  "make a break for it",
  "small fry",
  "hang tough",
  "accident waiting to happen",
  "never in a million years",
  "heavy hitter",
  "in the cross hairs",
  "make my mark",
  "take ten",
  "sitting pretty",
  "meeting of the minds",
  "work my fingers to the bone",
  "above and beyond",
  "playing with fire",
  "sick as a dog",
  "drawing a blank",
  "cry your eyes out",
  "turn the tables",
  "hit a wall",
  "a whale of a time",
  "keep an eye peeled",
  "turn a blind eye",
  "jump through hoops",
  "a good deal",
  "the dead of winter",
  "shaking in my boots",
  "the deck is stacked against me",
  "couch potato",
  "buying time",
  "upset the apple cart",
  "a tall order",
  "blinded by love",
  "a sight for sore eyes",
  "go to the mattresses",
  "no holds barred",
  "eagle eyed",
  "fifth wheel",
  "set the bar too high",
  "go ape",
  "break the ice",
  "helicopter parenting",
  "feel like a million bucks",
  "your mileage may vary",
  "chop shop",
  "fall prey to",
  "mother nature",
  "dead shot",
  "any tom dick or harry",
  "walking on eggshells",
  "knock their socks off",
  "it fell off a truck",
  "kiss and make up",
  "think big",
  "a greasy spoon",
  "test the waters",
  "take a gander",
  "playing hardball",
  "bone dry",
  "keep your powder dry",
  "dead ringer",
  "a busy bee",
  "a cat nap",
  "read the tea leaves",
  "quick and dirty",
  "touch base",
  "twist the knife",
  "a stick in the mud",
  "hanging on by a thread",
  "act of congress",
  "go under the knife",
  "a kid in a candy store",
  "throw me under the bus",
  "cut corners",
  "go the extra mile",
  "you can take it to the bank",
  "pick a fight",
  "get my ducks in a row",
  "a day late and a dollar short",
  "the point of no return",
  "ugly duckling",
  "pain in the neck",
  "a sitting duck",
  "hatchet job",
  "play ball",
  "fly high",
  "all hell breaks loose",
  "cat on a hot tin roof",
  "go bananas",
  "dead eye",
  "a nail biter",
  "start with a clean slate",
  "bed of roses",
  "the last laugh",
  "my hands are tied",
  "in full swing",
  "make nice",
  "step up to the plate",
  "pecking order",
  "the real mccoy",
  "sit tight",
  "your number is up",
  "drop a line",
  "red herring",
  "green as grass",
  "a plum job",
  "take the fifth",
  "tear my hair out",
  "bad taste in my mouth",
  "monday morning quarterback",
  "teach an old dog new tricks",
  "bite the hand that feeds you",
  "grease the wheels",
  "under the radar",
  "trash talk",
  "sweeten the pot",
  "get a word in edgewise",
  "another nail in the coffin",
  "come out swinging",
  "go cold turkey",
  "get in on the ground floor",
  "pull yourself together",
  "in a rut",
  "fox in the henhouse",
  "bar fly",
  "take a flyer",
  "a page turner",
  "not playing with a full deck",
  "bitter pill to swallow",
  "spin a yarn",
  "move heaven and earth",
  "flesh and blood",
  "bells and whistles",
  "shoot from the hip",
  "lose my touch",
  "bad blood",
  "lose the thread",
  "chew the fat",
  "all in good time",
  "dodge a bullet",
  "a little bird told me",
  "back forty",
  "loaded for bear",
  "bottom of the barrel",
  "nickel and dime",
  "hit the sack",
  "no skin off my back",
  "go viral",
  "have a lead foot",
  "mend fences",
  "all that jazz",
  "a perfect storm",
  "shell game",
  "stiff necked",
  "set the world on fire",
  "the fourth estate",
  "set in stone",
  "drive me up the wall",
  "swim with sharks",
  "head and shoulders above",
  "shot across the bow",
  "foot and mouth disease",
  "all the marbles",
  "an early bird",
  "home truths",
  "tough sledding",
  "bucket list",
  "clear the air",
  "a short fuse",
  "sharp as a tack",
  "call the shots",
  "see the forest for the trees",
  "bigger fish to fry",
  "eat humble pie",
  "agree to disagree",
  "two a penny",
  "in broad daylight",
  "a lone wolf",
  "home away from home",
  "give my two cents",
  "basket case",
  "love at first sight",
  "a bone to pick",
  "lame duck",
  "best thing since sliced bread",
  "bring home the bacon",
  "amateur hour",
  "come to grips with",
  "in the hot seat",
  "get the runaround",
  "fall on my sword",
  "water under the bridge",
  "have a nose for it",
  "it takes two to tango",
  "dog eat dog",
  "a head start",
  "an eye for an eye",
  "asleep at the wheel",
  "from pillar to post",
  "an axe to grind",
  "rotten to the core",
  "a cut above",
  "in a pickle",
  "the genie is out of the bottle",
  "go out on a limb",
  "drain the swamp",
  "follow your heart",
  "a penny for your thoughts",
  "rub it in",
  "passing fancy",
  "a tough row to hoe",
  "look the other way",
  "baby boomer",
  "rake over the coals",
  "dance with the devil",
  "powder keg",
  "you clean up nicely",
  "step up your game",
  "hightail it out",
  "take the high road",
  "weekend warrior",
  "lend an ear",
  "cut the mustard",
  "in the toilet",
  "put the brakes on",
  "on the back burner",
  "light a fire",
  "take it on the chin",
  "cherry pick",
  "on top of the world",
  "lick my wounds",
  "dressed up and nowhere to go",
  "running on fumes",
  "throw the game",
  "wet behind the ears",
  "puppy dog eyes",
  "drive a hard bargain",
  "beyond the shadow of a doubt",
  "drink the kool aid",
  "running out of steam",
  "behind the scenes",
  "blow off steam",
  "turn on a dime",
  "quick as a flash",
  "cash in my chips",
  "a leg up",
  "soak up the sun",
  "behind the times",
  "spoiling for a fight",
  "puddle jumper",
  "pick up the slack",
  "live large",
  "a stitch in time saves nine",
  "throw the book at",
  "just around the corner",
  "drop the ball",
  "go belly up",
  "a barrel of laughs",
  "a witch hunt",
  "a dog in the manger",
  "one too many",
  "back the wrong horse",
  "at the end of my rope",
  "make ends meet",
  "tread water",
  "worn to a frazzle",
  "when in doubt leave it out",
  "in one fell swoop",
  "keep it at bay",
  "every man for himself",
  "a pet peeve",
  "take your time",
  "miss the boat",
  "in my wheelhouse",
  "all bark and no bite",
  "no love lost",
  "bean counters",
  "acquired taste",
  "black eye",
  "hit the spot",
  "just what the doctor ordered",
  "eat crow",
  "go nuclear",
  "a hot mess",
  "the cat that got the cream",
  "victory lap",
  "hit it out of the park",
  "slower than molasses",
  "it is in the bag",
  "to bear fruit",
  "raise the bar",
  "make hay while the sun shines",
  "to the letter",
  "hands down",
  "slippery slope",
  "all eyes on me",
  "alive and kicking",
  "armed to the teeth",
  "nailing jelly to a wall",
  "come to terms with",
  "son of a gun",
  "under your spell",
  "draw the line",
  "loose cannon",
  "take a deep dive",
  "jump on the bandwagon",
  "across the pond",
  "throw a wet blanket on it",
  "spinning my wheels",
  "pop the question",
  "cast the first stone",
  "a chip on my shoulder",
  "champ at the bit",
  "all talk and no trousers",
  "make my day",
  "straight arrow",
  "school of hard knocks",
  "shoot myself in the foot",
  "a game of chicken",
  "all bets are off",
  "bring a knife to a gunfight",
  "burning bridges",
  "piping hot",
  "hit the books",
  "around the clock",
  "hit the roof",
  "tight lipped",
  "batten down the hatches",
  "by a whisker",
  "wet blanket",
  "thirty thousand foot view",
  "what goes around comes around",
  "kick the bucket",
  "wild goose chase",
  "jump in with both feet",
  "man cave",
  "elephant in the room",
  "your guess is as good as mine",
  "taking candy from a baby",
  "hold the phone",
  "every dog has his day",
  "above the law",
  "rock bottom",
  "in a nutshell",
  "flew the coop",
  "a guilty pleasure",
  "acknowledge the corn",
  "pay lip service",
  "get carried away",
  "the jig is up",
  "pure as the driven snow",
  "in seventh heaven",
  "change your tune",
  "up to scratch",
  "stand on your own two feet",
  "leave me in the lurch",
  "bump in the road",
  "castle in the air",
  "dead heat",
  "baby blues",
  "stab me in the back",
  "in a heartbeat",
  "fire in the belly",
  "spick and span",
  "fed up with",
  "heads up",
  "peaches and cream",
  "like a moth to a flame",
  "zip your lip",
  "holding all the aces",
  "look what the cat dragged in",
  "shift gears",
  "wake up and smell the coffee",
  "in the long run",
  "too many to shake a stick at",
  "hot potato",
  "jam session",
  "a smoking gun",
  "as poor as a church mouse",
  "a dark horse",
  "at the eleventh hour",
  "give them the cold shoulder",
  "six feet under",
  "chill out",
  "third rail",
  "let off steam",
  "tell it like it is",
  "in the same boat",
  "up to snuff",
  "beauty is only skin deep",
  "life is a bowl of cherries",
  "bare my soul",
  "feather in my cap",
  "feast your eyes on",
  "chickens coming home to roost",
  "grease monkey",
  "a changing of the guard",
  "when in rome",
  "taste of your own medicine",
  "loan shark",
  "fashion forward",
  "one for the road",
  "add insult to injury",
  "all the rage",
  "all sizzle and no steak",
  "pass the buck",
  "learn the ropes",
  "pedal to the metal",
  "kith and kin",
  "sour grapes",
  "my dogs are barking",
  "fit as a fiddle",
  "in the nick of time",
  "the cutting edge",
  "cut your teeth",
  "roll the dice on",
  "catch some rays",
  "hit the big time",
  "a hail mary",
  "with bells on",
  "draw a line in the sand",
  "when the chips are down",
  "tempest in a teapot",
  "hit the nail on the head",
  "tighten the screws",
  "cry wolf",
  "break the bank",
  "in for a penny in for a pound",
  "top banana",
  "all ears",
  "join the club",
  "as pale as a ghost",
  "wet your whistle",
  "in my element",
  "all hat and no cattle",
  "a dog in the fight",
  "down the road",
  "my way or the highway",
  "zig when you should zag",
  "cool cat",
  "jump the gun",
  "put down roots",
  "blue light special",
  "watering hole",
  "raise the roof",
  "a dirty look",
  "early bird",
  "fly off the handle",
  "a lot on my plate",
  "chin music",
  "bail out",
  "stick your nose into something",
  "a weight off your shoulders",
  "lock horns",
  "put words in my mouth",
  "second stringer",
  "arm candy",
  "roll with the punches",
  "behind the eight ball",
  "from soup to nuts",
  "aha moment",
  "wash your hands of it",
  "see eye to eye",
  "small potatoes",
  "hit the jackpot",
  "for a song",
  "a charley horse",
  "puppy love",
  "all mouth and no trousers",
  "not ready for prime time",
  "strike a chord",
  "right under my nose",
  "shooting fish in a barrel",
  "raise red flags",
  "call it a night",
  "in the blink of an eye",
  "all and sundry",
  "give them an earful",
  "throw a wrench into",
  "for crying out loud",
  "tip my hand",
  "bury your head in the sand",
  "pull out all the stops",
  "pull the plug on",
  "in a fog",
  "drag my heels",
  "father figure",
  "paddle my own canoe",
  "letter of the law",
  "flash in the pan",
  "egg on your face",
  "any port in a storm",
  "down in the dumps",
  "break out in a cold sweat",
  "fish out of water",
  "the cherry on top",
  "make waves",
  "turn someone inside out",
  "hit the ground running",
  "call it a day",
  "find your feet",
  "a bit much",
  "cook my goose",
  "claim to fame",
  "nice chunk of change",
  "get bent out of shape",
  "turn the corner",
  "new wrinkle",
  "break a leg",
  "best of both worlds",
  "music to my ears",
  "swim against the tide",
  "drag your feet",
  "eighty six it",
  "eager beaver",
  "bull in a china shop",
  "swan song",
  "sure fire",
  "blood and thunder",
  "put a thumb on the scale",
  "in a jam",
  "cat and mouse",
  "play the percentages",
  "throw down the gauntlet",
  "come rain or shine",
  "move the needle",
  "whistle past the graveyard",
  "change horses in midstream",
  "turnabout is fair play",
  "living under a rock",
  "spitting into the wind",
  "under the table",
  "a tear jerker",
  "boys will be boys",
  "a scaredy cat",
  "take the cake",
  "no rhyme or reason",
  "like father like son",
  "the cat is out of the bag",
  "from the bottom of my heart",
  "fat cat",
  "crunch the numbers",
  "cold day in hell",
  "come clean",
  "i smell a rat",
  "simmer down",
  "shooting your mouth off",
  "square the circle",
  "gets my goat",
  "coming down the pike",
  "beat around the bush",
  "hot on the heels of",
  "a hundred and ten percent",
  "nose to the grindstone",
  "heavens open",
  "rub it in my face",
  "a notch above",
  "having a ball",
  "at loggerheads",
  "cooking up a storm",
  "keep it under your hat",
  "take me to the cleaners",
  "add fuel to the fire",
  "that ship has sailed",
  "fight like cat and dog",
  "lower the boom",
  "that touched my heart",
  "laughter is the best medicine",
  "the coast is clear",
  "cheap shot",
  "when hell freezes over",
  "even steven",
  "babe in the woods",
];

export const TOTAL_PHRASES = 1310;

// Reference date: April 18, 2022
export const REFERENCE_DATE = new Date(2022, 3, 18); // Month is 0-indexed

/**
 * Calculate the game number for a given date and time
 * Morning (before 12:00): odd numbers (1, 3, 5...)
 * Afternoon (12:00+): even numbers (2, 4, 6...)
 */
export function getGameNumber(date: Date): number {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  
  const ref = new Date(REFERENCE_DATE);
  ref.setHours(0, 0, 0, 0);
  
  const diffMs = d.getTime() - ref.getTime();
  const days = Math.ceil(diffMs / 86400000);
  
  const hour = date.getHours();
  return 2 * days + (hour < 12 ? 1 : 2);
}

/**
 * Get the phrase index for a given date and time
 */
export function getPhraseIndex(date: Date): number {
  const gameNumber = getGameNumber(date);
  return ((gameNumber % TOTAL_PHRASES) + TOTAL_PHRASES) % TOTAL_PHRASES; // Handle negative modulo
}

/**
 * Get the phrase for a given date and time
 */
export function getPhrase(date: Date): string {
  const index = getPhraseIndex(date);
  return PHRASES[index];
}

/**
 * Get the answer for a specific date and session (morning/afternoon)
 */
export function getAnswerForDate(date: Date, session: 'morning' | 'afternoon'): { phrase: string; index: number } {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  
  const ref = new Date(REFERENCE_DATE);
  ref.setHours(0, 0, 0, 0);
  
  const diffMs = d.getTime() - ref.getTime();
  const days = Math.ceil(diffMs / 86400000);
  
  const gameNumber = session === 'morning' 
    ? 2 * days + 1 
    : 2 * days + 2;
  
  const index = ((gameNumber % TOTAL_PHRASES) + TOTAL_PHRASES) % TOTAL_PHRASES;
  return {
    phrase: PHRASES[index],
    index
  };
}

/**
 * Get date info for display
 */
export function formatDateInfo(date: Date): { 
  dateStr: string; 
  morningPhrase: string; 
  afternoonPhrase: string;
  morningIndex: number;
  afternoonIndex: number;
} {
  const morning = getAnswerForDate(date, 'morning');
  const afternoon = getAnswerForDate(date, 'afternoon');
  
  return {
    dateStr: date.toISOString().split('T')[0],
    morningPhrase: morning.phrase,
    afternoonPhrase: afternoon.phrase,
    morningIndex: morning.index,
    afternoonIndex: afternoon.index
  };
}
